package com.fastcoo.fastcoopickerapp.Activity;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;

import android.app.ProgressDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.fastcoo.fastcoopickerapp.Adaptor.AutoGenerated_Adaptor;
import com.fastcoo.fastcoopickerapp.Adaptor.PickupList_Adaptor;
import com.fastcoo.fastcoopickerapp.Interface.Retrofit_Data;
import com.fastcoo.fastcoopickerapp.Model.Autogenerated_Details;
import com.fastcoo.fastcoopickerapp.Model.Autogenerated_Main;
import com.fastcoo.fastcoopickerapp.Model.Picklist_Main;
import com.fastcoo.fastcoopickerapp.Model.SinglePickup_Result;
import com.fastcoo.fastcoopickerapp.Model.SinglePickup_list;
import com.fastcoo.fastcoopickerapp.R;
import com.fastcoo.fastcoopickerapp.Service.Retrofit_Service;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;

import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class AutoGeneratedPickup extends AppCompatActivity implements SwipeRefreshLayout.OnRefreshListener {

    SharedPreferences pickuplist_preference;
    SharedPreferences.Editor pickuplist_editor;
    String user_id="";
    String id;
    RecyclerView recyclerView;
    AutoGenerated_Adaptor adaptor;
    ArrayList<Autogenerated_Details> result1;
    private static ProgressDialog mProgressDialog;
    TextView no_data;
    Toolbar toolbar;
    SwipeRefreshLayout mSwipeRefreshLayout;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_auto_generated_pickup);
        recyclerView= findViewById(R.id.recycler_autopickup_list);
        pickuplist_preference =this.getApplicationContext().getSharedPreferences("MyPref",MODE_PRIVATE);
        pickuplist_editor= pickuplist_preference.edit();
        user_id= pickuplist_preference.getString("user_id",null);
        no_data= findViewById(R.id.tv_no_data_auto);
        toolbar= findViewById(R.id.toolbar_autopickup);
        setSupportActionBar(toolbar);
        mSwipeRefreshLayout = (SwipeRefreshLayout) findViewById(R.id.swipe_container);
        mSwipeRefreshLayout.setOnRefreshListener((SwipeRefreshLayout.OnRefreshListener) AutoGeneratedPickup.this);
        mSwipeRefreshLayout.setColorSchemeResources(R.color.colorPrimary,
                android.R.color.holo_green_dark,
                android.R.color.holo_orange_dark,
                android.R.color.holo_blue_dark);
        getSupportActionBar().setHomeButtonEnabled(true);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getAutoList();
    }

    public void getAutoList(){
        mProgressDialog = ProgressDialog.show(this, "PickList Id", "Loading..");
        mProgressDialog.setCancelable(false);
        mProgressDialog.show();
        Retrofit_Data data= Retrofit_Service.getRetrofitInstance().create(Retrofit_Data.class);
        Call<Autogenerated_Main> call= data.getAutoPickup_List(user_id);
        call.enqueue(new Callback<Autogenerated_Main>() {

            @Override
            public void onResponse(Call<Autogenerated_Main> call, Response<Autogenerated_Main> response) {

                response.body();
                Autogenerated_Details result= new Autogenerated_Details();
                if (response.body().getStatus().equals(200)){

                    for(int i=0;i<=response.body().getResult().size()-1;i++){
                        String pickup_id= response.body().getResult().get(i).getPickupId();
                        String total= response.body().getResult().get(i).getTotal();
                        String total_pending= response.body().getResult().get(i).getTotalPending();
                        result.setPickupId(pickup_id);
                        result.setTotal(total);
                        result.setTotalPending(total_pending);
                        result1=(ArrayList<Autogenerated_Details>) response.body().getResult();
                        adaptor= new AutoGenerated_Adaptor(result1,AutoGeneratedPickup.this);
                        recyclerView.setLayoutManager(new GridLayoutManager(AutoGeneratedPickup.this,1, LinearLayoutManager.VERTICAL,false));
                        recyclerView.setAdapter(adaptor);
                        Collections.sort(result1,Autogenerated_Details.detail);
                        adaptor.notifyDataSetChanged();
                        mProgressDialog.dismiss();


                    }


                }else {
                    recyclerView.setVisibility(View.INVISIBLE);
                    no_data.setVisibility(View.VISIBLE);
                    mProgressDialog.dismiss();

                }
            }

            @Override
            public void onFailure(Call<Autogenerated_Main> call, Throwable t) {
                Toast.makeText(AutoGeneratedPickup.this,t.getLocalizedMessage(), Toast.LENGTH_LONG).show();

            }
        });
    }



    @Override
    public void onRefresh() {
        adaptor = new AutoGenerated_Adaptor(result1,this);
        getAutoList();
        mSwipeRefreshLayout.setRefreshing(false);
    }

    @Override
    public boolean onSupportNavigateUp() {

        onBackPressed();
        overridePendingTransition(R.anim.fade_in, R.anim.fade_out);
        return true;
    }
    @Override
    public void onBackPressed() {

        Intent intent = new Intent(this,Dashboard.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        startActivity(intent);
        AutoGeneratedPickup.this.finish();
    }
}