package com.fastcoo.fastcoopickerapp.Activity;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.LinearLayout;
import androidx.appcompat.app.AppCompatActivity;
import com.fastcoo.fastcoopickerapp.R;

public class Dashboard extends AppCompatActivity {

    SharedPreferences dashboard_preference;
    SharedPreferences.Editor dashboard_editor;
    String user_id="";
    LinearLayout singlepickup_list,completed,logout,autogenerated;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_dashboard);
        singlepickup_list= findViewById(R.id.linear_single_pickuplist_id);
        completed= findViewById(R.id.linear_complete_pickup);
        logout= findViewById(R.id.linear_logout);
        dashboard_preference =getApplicationContext().getSharedPreferences("MyPref",MODE_PRIVATE);
        dashboard_editor= dashboard_preference.edit();
        user_id= dashboard_preference.getString("user_id",null);
        autogenerated= findViewById(R.id.linear_autopickup);
        Log.d("user_id",user_id);

        singlepickup_list.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent goto_singlePickup_list= new Intent(Dashboard.this, PickupList.class);
                goto_singlePickup_list.putExtra("user_id",user_id);
                startActivity(goto_singlePickup_list);
            }
        });

        completed.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent complete= new Intent(Dashboard.this,CompletedList.class);
                startActivity(complete);
            }
        });

        logout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                dashboard_editor.clear();
                dashboard_editor.commit();

                Intent logout= new Intent(Dashboard.this, MainActivity.class);
                startActivity(logout);
                finish();
            }
        });


        autogenerated.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent auto= new Intent(Dashboard.this,AutoGeneratedPickup.class);
                startActivity(auto);

            }
        });
    }
}